CChart.o: CChart.cpp stdafx.h CSignal.h CGraphics.h CWindow.h Resource.h \
 CChartWindow.h CChart.h CSimulation.h CModel.h CGDI.h
CChartWindow.o: CChartWindow.cpp stdafx.h CChartWindow.h CWindow.h \
 Resource.h CChart.h CSimulation.h CSignal.h CModel.h CGraphics.h CGDI.h \
 CSignalsFile.h CFile.h
CControls.o: CControls.cpp stdafx.h CPropWindow.h CWindow.h Resource.h \
 CControls.h CSimulation.h CSignal.h CModel.h CProperties.h
CFile.o: CFile.cpp stdafx.h CFile.h
CGDI.o: CGDI.cpp stdafx.h CGDI.h CWindow.h Resource.h CGraphics.h
CGenAlg.o: CGenAlg.cpp stdafx.h CGenAlg.h
CGraphics.o: CGraphics.cpp stdafx.h CGraphics.h CWindow.h Resource.h
CModel.o: CModel.cpp stdafx.h CModel.h CSimulation.h CSignal.h
CNeuralNet.o: CNeuralNet.cpp stdafx.h CNeuralNet.h
CPolesWindow.o: CPolesWindow.cpp stdafx.h CPolesWindow.h CChartWindow.h \
 CWindow.h Resource.h CChart.h CSimulation.h CSignal.h CModel.h \
 CGraphics.h CGDI.h
CPropWindow.o: CPropWindow.cpp stdafx.h CPropWindow.h CWindow.h \
 Resource.h CControls.h CSimulation.h CSignal.h CModel.h CProperties.h \
 CFile.h
CProperties.o: CProperties.cpp stdafx.h CProperties.h
CSignal.o: CSignal.cpp stdafx.h CSignal.h
CSignalsFile.o: CSignalsFile.cpp stdafx.h CSignalsFile.h CFile.h \
 CSignal.h CChart.h CSimulation.h CModel.h
CSimulation.o: CSimulation.cpp stdafx.h CSimulation.h CSignal.h CModel.h
CWindow.o: CWindow.cpp stdafx.h CWindow.h Resource.h
MDosSim.o: MDosSim.cpp stdafx.h MDosSim.h CModel.h CSimulation.h \
 CSignal.h dos2win.h
MIndMach.o: MIndMach.cpp stdafx.h MIndMach.h CModel.h CSimulation.h \
 CSignal.h
MIndMachObs.o: MIndMachObs.cpp stdafx.h MIndMachObs.h CModel.h \
 CSimulation.h CSignal.h
MPoles.o: MPoles.cpp stdafx.h MPoles.h CModel.h CSimulation.h CSignal.h \
 MIndMachObs.h armadillo/armadillo.h armadillo/armadillo_bits/config.hpp \
 armadillo/armadillo_bits/compiler_setup.hpp \
 armadillo/armadillo_bits/undefine_conflicts.hpp \
 armadillo/armadillo_bits/include_atlas.hpp \
 armadillo/armadillo_bits/forward_bones.hpp \
 armadillo/armadillo_bits/arma_static_check.hpp \
 armadillo/armadillo_bits/typedef.hpp \
 armadillo/armadillo_bits/typedef_blas_int.hpp \
 armadillo/armadillo_bits/format_wrap.hpp \
 armadillo/armadillo_bits/arma_version.hpp \
 armadillo/armadillo_bits/arma_config.hpp \
 armadillo/armadillo_bits/traits.hpp \
 armadillo/armadillo_bits/promote_type.hpp \
 armadillo/armadillo_bits/upgrade_val.hpp \
 armadillo/armadillo_bits/restrictors.hpp \
 armadillo/armadillo_bits/access.hpp armadillo/armadillo_bits/memory.hpp \
 armadillo/armadillo_bits/span.hpp armadillo/armadillo_bits/constants.hpp \
 armadillo/armadillo_bits/constants_compat.hpp \
 armadillo/armadillo_bits/Base_bones.hpp \
 armadillo/armadillo_bits/BaseCube_bones.hpp \
 armadillo/armadillo_bits/blas_bones.hpp \
 armadillo/armadillo_bits/lapack_bones.hpp \
 armadillo/armadillo_bits/atlas_bones.hpp \
 armadillo/armadillo_bits/blas_wrapper.hpp \
 armadillo/armadillo_bits/lapack_wrapper.hpp \
 armadillo/armadillo_bits/atlas_wrapper.hpp \
 armadillo/armadillo_bits/cond_rel_bones.hpp \
 armadillo/armadillo_bits/arrayops_bones.hpp \
 armadillo/armadillo_bits/podarray_bones.hpp \
 armadillo/armadillo_bits/auxlib_bones.hpp \
 armadillo/armadillo_bits/injector_bones.hpp \
 armadillo/armadillo_bits/Mat_bones.hpp \
 armadillo/armadillo_bits/Col_bones.hpp \
 armadillo/armadillo_bits/Row_bones.hpp \
 armadillo/armadillo_bits/Cube_bones.hpp \
 armadillo/armadillo_bits/typedef_fixed.hpp \
 armadillo/armadillo_bits/field_bones.hpp \
 armadillo/armadillo_bits/subview_bones.hpp \
 armadillo/armadillo_bits/subview_elem1_bones.hpp \
 armadillo/armadillo_bits/subview_elem2_bones.hpp \
 armadillo/armadillo_bits/subview_field_bones.hpp \
 armadillo/armadillo_bits/subview_cube_bones.hpp \
 armadillo/armadillo_bits/diagview_bones.hpp \
 armadillo/armadillo_bits/diskio_bones.hpp \
 armadillo/armadillo_bits/wall_clock_bones.hpp \
 armadillo/armadillo_bits/running_stat_bones.hpp \
 armadillo/armadillo_bits/running_stat_vec_bones.hpp \
 armadillo/armadillo_bits/Op_bones.hpp \
 armadillo/armadillo_bits/OpCube_bones.hpp \
 armadillo/armadillo_bits/eOp_bones.hpp \
 armadillo/armadillo_bits/eOpCube_bones.hpp \
 armadillo/armadillo_bits/mtOp_bones.hpp \
 armadillo/armadillo_bits/mtOpCube_bones.hpp \
 armadillo/armadillo_bits/Glue_bones.hpp \
 armadillo/armadillo_bits/eGlue_bones.hpp \
 armadillo/armadillo_bits/mtGlue_bones.hpp \
 armadillo/armadillo_bits/GlueCube_bones.hpp \
 armadillo/armadillo_bits/eGlueCube_bones.hpp \
 armadillo/armadillo_bits/mtGlueCube_bones.hpp \
 armadillo/armadillo_bits/eop_core_bones.hpp \
 armadillo/armadillo_bits/eglue_core_bones.hpp \
 armadillo/armadillo_bits/Gen_bones.hpp \
 armadillo/armadillo_bits/GenCube_bones.hpp \
 armadillo/armadillo_bits/op_diagmat_bones.hpp \
 armadillo/armadillo_bits/op_diagvec_bones.hpp \
 armadillo/armadillo_bits/op_dot_bones.hpp \
 armadillo/armadillo_bits/op_inv_bones.hpp \
 armadillo/armadillo_bits/op_htrans_bones.hpp \
 armadillo/armadillo_bits/op_max_bones.hpp \
 armadillo/armadillo_bits/op_min_bones.hpp \
 armadillo/armadillo_bits/op_mean_bones.hpp \
 armadillo/armadillo_bits/op_median_bones.hpp \
 armadillo/armadillo_bits/op_sort_bones.hpp \
 armadillo/armadillo_bits/op_sum_bones.hpp \
 armadillo/armadillo_bits/op_stddev_bones.hpp \
 armadillo/armadillo_bits/op_strans_bones.hpp \
 armadillo/armadillo_bits/op_var_bones.hpp \
 armadillo/armadillo_bits/op_repmat_bones.hpp \
 armadillo/armadillo_bits/op_reshape_bones.hpp \
 armadillo/armadillo_bits/op_resize_bones.hpp \
 armadillo/armadillo_bits/op_cov_bones.hpp \
 armadillo/armadillo_bits/op_cor_bones.hpp \
 armadillo/armadillo_bits/op_shuffle_bones.hpp \
 armadillo/armadillo_bits/op_prod_bones.hpp \
 armadillo/armadillo_bits/op_pinv_bones.hpp \
 armadillo/armadillo_bits/op_dotext_bones.hpp \
 armadillo/armadillo_bits/op_flip_bones.hpp \
 armadillo/armadillo_bits/op_princomp_bones.hpp \
 armadillo/armadillo_bits/op_misc_bones.hpp \
 armadillo/armadillo_bits/op_relational_bones.hpp \
 armadillo/armadillo_bits/op_find_bones.hpp \
 armadillo/armadillo_bits/op_chol_bones.hpp \
 armadillo/armadillo_bits/op_cx_scalar_bones.hpp \
 armadillo/armadillo_bits/op_trimat_bones.hpp \
 armadillo/armadillo_bits/op_cumsum_bones.hpp \
 armadillo/armadillo_bits/op_symmat_bones.hpp \
 armadillo/armadillo_bits/op_hist_bones.hpp \
 armadillo/armadillo_bits/op_unique_bones.hpp \
 armadillo/armadillo_bits/glue_times_bones.hpp \
 armadillo/armadillo_bits/glue_mixed_bones.hpp \
 armadillo/armadillo_bits/glue_cov_bones.hpp \
 armadillo/armadillo_bits/glue_cor_bones.hpp \
 armadillo/armadillo_bits/glue_kron_bones.hpp \
 armadillo/armadillo_bits/glue_cross_bones.hpp \
 armadillo/armadillo_bits/glue_join_bones.hpp \
 armadillo/armadillo_bits/glue_relational_bones.hpp \
 armadillo/armadillo_bits/glue_solve_bones.hpp \
 armadillo/armadillo_bits/glue_conv_bones.hpp \
 armadillo/armadillo_bits/glue_toeplitz_bones.hpp \
 armadillo/armadillo_bits/glue_hist_bones.hpp \
 armadillo/armadillo_bits/glue_histc_bones.hpp \
 armadillo/armadillo_bits/debug.hpp \
 armadillo/armadillo_bits/cmath_wrap.hpp \
 armadillo/armadillo_bits/unwrap.hpp \
 armadillo/armadillo_bits/unwrap_cube.hpp \
 armadillo/armadillo_bits/Proxy.hpp \
 armadillo/armadillo_bits/ProxyCube.hpp \
 armadillo/armadillo_bits/diagmat_proxy.hpp \
 armadillo/armadillo_bits/strip.hpp armadillo/armadillo_bits/Op_meat.hpp \
 armadillo/armadillo_bits/OpCube_meat.hpp \
 armadillo/armadillo_bits/mtOp_meat.hpp \
 armadillo/armadillo_bits/mtOpCube_meat.hpp \
 armadillo/armadillo_bits/Glue_meat.hpp \
 armadillo/armadillo_bits/GlueCube_meat.hpp \
 armadillo/armadillo_bits/eop_aux.hpp \
 armadillo/armadillo_bits/eOp_meat.hpp \
 armadillo/armadillo_bits/eOpCube_meat.hpp \
 armadillo/armadillo_bits/eGlue_meat.hpp \
 armadillo/armadillo_bits/eGlueCube_meat.hpp \
 armadillo/armadillo_bits/mtGlue_meat.hpp \
 armadillo/armadillo_bits/mtGlueCube_meat.hpp \
 armadillo/armadillo_bits/Base_meat.hpp \
 armadillo/armadillo_bits/BaseCube_meat.hpp \
 armadillo/armadillo_bits/Gen_meat.hpp \
 armadillo/armadillo_bits/GenCube_meat.hpp \
 armadillo/armadillo_bits/arma_ostream_bones.hpp \
 armadillo/armadillo_bits/arma_ostream_meat.hpp \
 armadillo/armadillo_bits/operator_plus.hpp \
 armadillo/armadillo_bits/operator_minus.hpp \
 armadillo/armadillo_bits/operator_times.hpp \
 armadillo/armadillo_bits/operator_schur.hpp \
 armadillo/armadillo_bits/operator_div.hpp \
 armadillo/armadillo_bits/operator_relational.hpp \
 armadillo/armadillo_bits/operator_cube_plus.hpp \
 armadillo/armadillo_bits/operator_cube_minus.hpp \
 armadillo/armadillo_bits/operator_cube_times.hpp \
 armadillo/armadillo_bits/operator_cube_schur.hpp \
 armadillo/armadillo_bits/operator_cube_div.hpp \
 armadillo/armadillo_bits/operator_cube_relational.hpp \
 armadillo/armadillo_bits/operator_ostream.hpp \
 armadillo/armadillo_bits/fn_conv_to.hpp \
 armadillo/armadillo_bits/fn_min.hpp armadillo/armadillo_bits/fn_max.hpp \
 armadillo/armadillo_bits/fn_accu.hpp armadillo/armadillo_bits/fn_sum.hpp \
 armadillo/armadillo_bits/fn_diagmat.hpp \
 armadillo/armadillo_bits/fn_diagvec.hpp \
 armadillo/armadillo_bits/fn_inv.hpp \
 armadillo/armadillo_bits/fn_trace.hpp \
 armadillo/armadillo_bits/fn_trans.hpp \
 armadillo/armadillo_bits/fn_det.hpp \
 armadillo/armadillo_bits/fn_log_det.hpp \
 armadillo/armadillo_bits/fn_eig.hpp armadillo/armadillo_bits/fn_lu.hpp \
 armadillo/armadillo_bits/fn_zeros.hpp \
 armadillo/armadillo_bits/fn_ones.hpp armadillo/armadillo_bits/fn_eye.hpp \
 armadillo/armadillo_bits/fn_misc.hpp \
 armadillo/armadillo_bits/fn_elem.hpp \
 armadillo/armadillo_bits/fn_norm.hpp armadillo/armadillo_bits/fn_dot.hpp \
 armadillo/armadillo_bits/fn_randu.hpp \
 armadillo/armadillo_bits/fn_randn.hpp \
 armadillo/armadillo_bits/fn_trig.hpp \
 armadillo/armadillo_bits/fn_mean.hpp \
 armadillo/armadillo_bits/fn_median.hpp \
 armadillo/armadillo_bits/fn_stddev.hpp \
 armadillo/armadillo_bits/fn_var.hpp armadillo/armadillo_bits/fn_sort.hpp \
 armadillo/armadillo_bits/fn_sort_index.hpp \
 armadillo/armadillo_bits/fn_strans.hpp \
 armadillo/armadillo_bits/fn_chol.hpp armadillo/armadillo_bits/fn_qr.hpp \
 armadillo/armadillo_bits/fn_svd.hpp \
 armadillo/armadillo_bits/fn_solve.hpp \
 armadillo/armadillo_bits/fn_repmat.hpp \
 armadillo/armadillo_bits/fn_reshape.hpp \
 armadillo/armadillo_bits/fn_resize.hpp \
 armadillo/armadillo_bits/fn_cov.hpp armadillo/armadillo_bits/fn_cor.hpp \
 armadillo/armadillo_bits/fn_shuffle.hpp \
 armadillo/armadillo_bits/fn_prod.hpp armadillo/armadillo_bits/fn_eps.hpp \
 armadillo/armadillo_bits/fn_pinv.hpp \
 armadillo/armadillo_bits/fn_rank.hpp \
 armadillo/armadillo_bits/fn_kron.hpp \
 armadillo/armadillo_bits/fn_flip.hpp \
 armadillo/armadillo_bits/fn_as_scalar.hpp \
 armadillo/armadillo_bits/fn_princomp.hpp \
 armadillo/armadillo_bits/fn_cross.hpp \
 armadillo/armadillo_bits/fn_join.hpp \
 armadillo/armadillo_bits/fn_conv.hpp \
 armadillo/armadillo_bits/fn_trunc_exp.hpp \
 armadillo/armadillo_bits/fn_trunc_log.hpp \
 armadillo/armadillo_bits/fn_toeplitz.hpp \
 armadillo/armadillo_bits/fn_trimat.hpp \
 armadillo/armadillo_bits/fn_cumsum.hpp \
 armadillo/armadillo_bits/fn_symmat.hpp \
 armadillo/armadillo_bits/fn_syl_lyap.hpp \
 armadillo/armadillo_bits/fn_hist.hpp \
 armadillo/armadillo_bits/fn_histc.hpp \
 armadillo/armadillo_bits/fn_unique.hpp armadillo/armadillo_bits/gemv.hpp \
 armadillo/armadillo_bits/gemm.hpp \
 armadillo/armadillo_bits/gemm_mixed.hpp \
 armadillo/armadillo_bits/eop_core_meat.hpp \
 armadillo/armadillo_bits/eglue_core_meat.hpp \
 armadillo/armadillo_bits/cond_rel_meat.hpp \
 armadillo/armadillo_bits/arrayops_meat.hpp \
 armadillo/armadillo_bits/podarray_meat.hpp \
 armadillo/armadillo_bits/auxlib_meat.hpp \
 armadillo/armadillo_bits/injector_meat.hpp \
 armadillo/armadillo_bits/Mat_meat.hpp \
 armadillo/armadillo_bits/Col_meat.hpp \
 armadillo/armadillo_bits/Row_meat.hpp \
 armadillo/armadillo_bits/Cube_meat.hpp \
 armadillo/armadillo_bits/field_meat.hpp \
 armadillo/armadillo_bits/subview_meat.hpp \
 armadillo/armadillo_bits/subview_elem1_meat.hpp \
 armadillo/armadillo_bits/subview_elem2_meat.hpp \
 armadillo/armadillo_bits/subview_field_meat.hpp \
 armadillo/armadillo_bits/subview_cube_meat.hpp \
 armadillo/armadillo_bits/diagview_meat.hpp \
 armadillo/armadillo_bits/diskio_meat.hpp \
 armadillo/armadillo_bits/wall_clock_meat.hpp \
 armadillo/armadillo_bits/running_stat_meat.hpp \
 armadillo/armadillo_bits/running_stat_vec_meat.hpp \
 armadillo/armadillo_bits/op_diagmat_meat.hpp \
 armadillo/armadillo_bits/op_diagvec_meat.hpp \
 armadillo/armadillo_bits/op_dot_meat.hpp \
 armadillo/armadillo_bits/op_inv_meat.hpp \
 armadillo/armadillo_bits/op_htrans_meat.hpp \
 armadillo/armadillo_bits/op_max_meat.hpp \
 armadillo/armadillo_bits/op_min_meat.hpp \
 armadillo/armadillo_bits/op_mean_meat.hpp \
 armadillo/armadillo_bits/op_median_meat.hpp \
 armadillo/armadillo_bits/op_sort_meat.hpp \
 armadillo/armadillo_bits/op_sum_meat.hpp \
 armadillo/armadillo_bits/op_stddev_meat.hpp \
 armadillo/armadillo_bits/op_strans_meat.hpp \
 armadillo/armadillo_bits/op_var_meat.hpp \
 armadillo/armadillo_bits/op_repmat_meat.hpp \
 armadillo/armadillo_bits/op_reshape_meat.hpp \
 armadillo/armadillo_bits/op_resize_meat.hpp \
 armadillo/armadillo_bits/op_cov_meat.hpp \
 armadillo/armadillo_bits/op_cor_meat.hpp \
 armadillo/armadillo_bits/op_shuffle_meat.hpp \
 armadillo/armadillo_bits/op_prod_meat.hpp \
 armadillo/armadillo_bits/op_pinv_meat.hpp \
 armadillo/armadillo_bits/op_dotext_meat.hpp \
 armadillo/armadillo_bits/op_flip_meat.hpp \
 armadillo/armadillo_bits/op_princomp_meat.hpp \
 armadillo/armadillo_bits/op_misc_meat.hpp \
 armadillo/armadillo_bits/op_relational_meat.hpp \
 armadillo/armadillo_bits/op_find_meat.hpp \
 armadillo/armadillo_bits/op_chol_meat.hpp \
 armadillo/armadillo_bits/op_cx_scalar_meat.hpp \
 armadillo/armadillo_bits/op_trimat_meat.hpp \
 armadillo/armadillo_bits/op_cumsum_meat.hpp \
 armadillo/armadillo_bits/op_symmat_meat.hpp \
 armadillo/armadillo_bits/op_hist_meat.hpp \
 armadillo/armadillo_bits/op_unique_meat.hpp \
 armadillo/armadillo_bits/glue_times_meat.hpp \
 armadillo/armadillo_bits/glue_mixed_meat.hpp \
 armadillo/armadillo_bits/glue_cov_meat.hpp \
 armadillo/armadillo_bits/glue_cor_meat.hpp \
 armadillo/armadillo_bits/glue_kron_meat.hpp \
 armadillo/armadillo_bits/glue_cross_meat.hpp \
 armadillo/armadillo_bits/glue_join_meat.hpp \
 armadillo/armadillo_bits/glue_relational_meat.hpp \
 armadillo/armadillo_bits/glue_solve_meat.hpp \
 armadillo/armadillo_bits/glue_conv_meat.hpp \
 armadillo/armadillo_bits/glue_toeplitz_meat.hpp \
 armadillo/armadillo_bits/glue_hist_meat.hpp \
 armadillo/armadillo_bits/glue_histc_meat.hpp
SimConfig.o: SimConfig.cpp stdafx.h SimConfig.h CChartWindow.h CWindow.h \
 Resource.h CChart.h CSimulation.h CSignal.h CModel.h CGraphics.h CGDI.h \
 CPropWindow.h CControls.h CProperties.h CFile.h MDosSim.h dos2win.h \
 dos_main.h
WinMain.o: WinMain.cpp stdafx.h WinMain.h resource.h SimConfig.h \
 CWindow.h Resource.h CChartWindow.h CChart.h CSimulation.h CSignal.h \
 CModel.h CGraphics.h CGDI.h CNeuralNet.h
dos2win.o: dos2win.cpp stdafx.h dos2win.h MDosSim.h CModel.h \
 CSimulation.h CSignal.h
stdafx.o: stdafx.cpp stdafx.h
